# Build stage
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g vite


# Copy source code
COPY . .

# Build the application and verify the build
RUN npm run build 


EXPOSE 5173 


CMD ["npm", "run", "prod"]


