# # Use an official node runtime as a parent image
# FROM node:18-alpine

# # Set the working directory in the container
# WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . .

# # Install the dependencies
# RUN npm install

# # Expose the port the app will run on
# EXPOSE 5173

# # Start the app
# CMD ["npm", "run", "prod"]
# Build Vite app
FROM node:18-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --mode production
