services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    volumes:
      - ./client/dist:/app/dist
    networks:
      - my-network

  server:
    build: ./server
    env_file:
      - ./server/.env.production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
