version: "3.8"
services:
  shagalphoto-backend:
    build: ./server
    ports:
      - "5001:5001"
    restart: always
    environment:
      - MONGO_URL=mongodb+srv://omeryaakov2:F59a7b4fa4@shagalphoto.v3genik.mongodb.net/?retryWrites=true&w=majority&appName=shagalphoto
    depends_on:
      - mongo

  shagalphoto-frontend:
    build: ./client
    ports:
      - "3001:3000"
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
