version: "3.8"

services:
  client:
    build: ./client
    expose:
      - "5173" # Only expose internally, NGINX will forward external traffic
    depends_on:
      - server
    networks:
      - my-network

  server:
    build: ./server
    expose:
      - "5000" # Only expose internally
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${DB_ATLAS}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
