services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - my-network

  server:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
